### ISSUE TITLE
Som användare vill jag kunna skanna in mig på en QR-kod på en Arctic Box. (sedan betalning)

### ISSUE THREAD

**Issue by mr-yukawa** [DenizeScheffold/ArcticWell#2]
Acceptanskriterier: 

Kunna skanna en QR-kod med kamera-appen och nå en URL.

URL:en ska leda till sidan “Boka bås”

**Comment by asakaryd** [comment]
![Skärmavbild 2022-04-06 kl  09 26 04](https://user-images.githubusercontent.com/103025623/161920078-8c1078a5-13a5-4360-ab71-037235211046.png)
