### ISSUE TITLE
Epic: Kunna betala min upplevelse med Swish (och kort?) genom min scanning (och betalning) kunna komma in i boxen (öppna dörren)

### ISSUE THREAD

**Issue by asakaryd** [DenizeScheffold/ArcticWell#4]

**Comment by Kalle-Rei** [comment]
This issue needs to be broken down into smaller pieces. Many of the steps in it are also duplicated in other issues: 
Opening the box was handled in issue #5 and #3 
Scanning a QR-code is handled in #2
