### ISSUE TITLE
Onboarding pages. Step 2 from landingpage

### ISSUE THREAD

**Issue by DenizeScheffold** [DenizeScheffold/ArcticWell#72]
Updated with info from @tedlagerman 's comment below:

As a user i want too navigate through the onboarding, so i can receive relevant and important information about the Company.
Acceptance criteria:
The frames should have 
* The same background/linear on all pages except the final one.
* Same dimensions on element/CTA buttons (Consistency)
* Please note different text in the CTA on the last page. It will lead to the mapview

**Comment by Kalle-Rei** [comment]
Fully implemented by @Hedesand as of https://github.com/DenizeScheffold/ArcticWell/commit/26d6356a295e02dcba2c65bdeb329af906dcb231
